- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import VPC variables
      include_vars: vars/vpc_setup.txt

    - name: create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout
