- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import VPC variables
      include_vars: vars/vpc_setup.txt

    - name: create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ pubSub1Cidr }}"

        map_public: yes
        resource_tags:
          Name: vprof-sub1
      register: subnet
